baseURL = "https://blog.stomsvik.com"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Keep IT Tidy"
theme = "submodule"
metaDataFormat = "yaml"
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[Params]
 favicon = "img/favicon.ico"
 homeTitle = "Keep IT Tidy"
 subtitle = "Notes about Microsoft, Security and scrambels"
 logo = "img/avatar-icon.png" # Expecting square dimensions
 rss = true
 readingTime = true
 useHLJS = true

 [Author]
   name = "Viggo stomsvik"
  website = "https://blog.stomsvik.com"
  email = "vstoms@gmail.com"
  github = "vstoms"
  twitter = "stoms"