baseURL = "https://blog.stomsvik.com"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Keep IT Tidy"
theme = "submodule"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true
favicon = "favicons/"

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true